package com.wingcode.suppermarket.model;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of customer.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Customer implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** customer_Id. */
	private Long customerId;

	/** customer_Code. */
	private String customerCode;

	/** customer_Name. */
	private String customerName;

	/** customer_Address. */
	private String customerAddress;

	/** customer_Contact. */
	private String customerContact;

	/** description. */
	private String description;

	/** on_Update. */
	private Date onUpdate;

	/** The set of sale_Invoice. */
	private Set<SaleInvoice> saleInvoiceSet;

	/**
	 * Constructor.
	 */
	public Customer() {
		this.saleInvoiceSet = new HashSet<>();
	}

	/**
	 * Set the customer_Id.
	 * 
	 * @param customerId
	 *            customer_Id
	 */
	public void setCustomerId(Long customerId) {
		this.customerId = customerId;
	}

	/**
	 * Get the customer_Id.
	 * 
	 * @return customer_Id
	 */
	public Long getCustomerId() {
		return this.customerId;
	}

	/**
	 * Set the customer_Code.
	 * 
	 * @param customerCode
	 *            customer_Code
	 */
	public void setCustomerCode(String customerCode) {
		this.customerCode = customerCode;
	}

	/**
	 * Get the customer_Code.
	 * 
	 * @return customer_Code
	 */
	public String getCustomerCode() {
		return this.customerCode;
	}

	/**
	 * Set the customer_Name.
	 * 
	 * @param customerName
	 *            customer_Name
	 */
	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	/**
	 * Get the customer_Name.
	 * 
	 * @return customer_Name
	 */
	public String getCustomerName() {
		return this.customerName;
	}

	/**
	 * Set the customer_Address.
	 * 
	 * @param customerAddress
	 *            customer_Address
	 */
	public void setCustomerAddress(String customerAddress) {
		this.customerAddress = customerAddress;
	}

	/**
	 * Get the customer_Address.
	 * 
	 * @return customer_Address
	 */
	public String getCustomerAddress() {
		return this.customerAddress;
	}

	/**
	 * Set the customer_Contact.
	 * 
	 * @param customerContact
	 *            customer_Contact
	 */
	public void setCustomerContact(String customerContact) {
		this.customerContact = customerContact;
	}

	/**
	 * Get the customer_Contact.
	 * 
	 * @return customer_Contact
	 */
	public String getCustomerContact() {
		return this.customerContact;
	}

	/**
	 * Set the description.
	 * 
	 * @param description
	 *            description
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * Get the description.
	 * 
	 * @return description
	 */
	public String getDescription() {
		return this.description;
	}

	/**
	 * Set the on_Update.
	 * 
	 * @param onUpdate
	 *            on_Update
	 */
	public void setOnUpdate(Date onUpdate) {
		this.onUpdate = onUpdate;
	}

	/**
	 * Get the on_Update.
	 * 
	 * @return on_Update
	 */
	public Date getOnUpdate() {
		return this.onUpdate;
	}

	/**
	 * Set the set of the sale_Invoice.
	 * 
	 * @param saleInvoiceSet
	 *            The set of sale_Invoice
	 */
	public void setSaleInvoiceSet(Set<SaleInvoice> saleInvoiceSet) {
		this.saleInvoiceSet = saleInvoiceSet;
	}

	/**
	 * Add the sale_Invoice.
	 * 
	 * @param saleInvoice
	 *            sale_Invoice
	 */
	public void addSaleInvoice(SaleInvoice saleInvoice) {
		this.saleInvoiceSet.add(saleInvoice);
	}

	/**
	 * Get the set of the sale_Invoice.
	 * 
	 * @return The set of sale_Invoice
	 */
	public Set<SaleInvoice> getSaleInvoiceSet() {
		return this.saleInvoiceSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((customerId == null) ? 0 : customerId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Customer other = (Customer) obj;
		if (customerId == null) {
			if (other.customerId != null) {
				return false;
			}
		} else if (!customerId.equals(other.customerId)) {
			return false;
		}
		return true;
	}

}
