package com.wingcode.suppermarket.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Model class of customer.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table(name = "customer")
//@JsonRootName(value = "Customer")
public class Customer extends AuditModel {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** customer_Id. */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "customer_Id", nullable = false, updatable = false)
	private Long customerId;

	/** customer_Code. */
	@Column(name = "customer_Code")
	private String customerCode;

	/** customer_Name. */
	@Column(name = "customer_Name")
	private String customerName;

	/** customer_Address. */
	@Column(name = "customer_Address")
	private String customerAddress;

	/** customer_Contact. */
	@Column(name = "customer_Contact")
	private String customerContact;

	/** description. */
	@Column(name = "description")
	private String description;

	/** on_Update. */
	@Column(name = "on_Update")
	private Date onUpdate;

	/**
	 * Set the customer_Id.
	 * 
	 * @param customerId
	 *            customer_Id
	 */
	public void setCustomerId(Long customerId) {
		this.customerId = customerId;
	}

	/**
	 * Get the customer_Id.
	 * 
	 * @return customer_Id
	 */
	public Long getCustomerId() {
		return this.customerId;
	}

	/**
	 * Set the customer_Code.
	 * 
	 * @param customerCode
	 *            customer_Code
	 */
	public void setCustomerCode(String customerCode) {
		this.customerCode = customerCode;
	}

	/**
	 * Get the customer_Code.
	 * 
	 * @return customer_Code
	 */
	public String getCustomerCode() {
		return this.customerCode;
	}

	/**
	 * Set the customer_Name.
	 * 
	 * @param customerName
	 *            customer_Name
	 */
	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	/**
	 * Get the customer_Name.
	 * 
	 * @return customer_Name
	 */
	public String getCustomerName() {
		return this.customerName;
	}

	/**
	 * Set the customer_Address.
	 * 
	 * @param customerAddress
	 *            customer_Address
	 */
	public void setCustomerAddress(String customerAddress) {
		this.customerAddress = customerAddress;
	}

	/**
	 * Get the customer_Address.
	 * 
	 * @return customer_Address
	 */
	public String getCustomerAddress() {
		return this.customerAddress;
	}

	/**
	 * Set the customer_Contact.
	 * 
	 * @param customerContact
	 *            customer_Contact
	 */
	public void setCustomerContact(String customerContact) {
		this.customerContact = customerContact;
	}

	/**
	 * Get the customer_Contact.
	 * 
	 * @return customer_Contact
	 */
	public String getCustomerContact() {
		return this.customerContact;
	}

	/**
	 * Set the description.
	 * 
	 * @param description
	 *            description
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * Get the description.
	 * 
	 * @return description
	 */
	public String getDescription() {
		return this.description;
	}

	/**
	 * Set the on_Update.
	 * 
	 * @param onUpdate
	 *            on_Update
	 */
	public void setOnUpdate(Date onUpdate) {
		this.onUpdate = onUpdate;
	}

	/**
	 * Get the on_Update.
	 * 
	 * @return on_Update
	 */
	public Date getOnUpdate() {
		return this.onUpdate;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((customerId == null) ? 0 : customerId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Customer other = (Customer) obj;
		if (customerId == null) {
			if (other.customerId != null) {
				return false;
			}
		} else if (!customerId.equals(other.customerId)) {
			return false;
		}
		return true;
	}

}
