package com.wingcode.suppermarket.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Model class of item_Group.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table(name = "item_group")
//@JsonRootName(value = "ItemGroup")
public class ItemGroup extends AuditModel {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** group_Name. */
	@Id	
	@Column(name = "group_Name", nullable = false, updatable = false)
	private String groupName;

	/**
	 * Set the group_Name.
	 * 
	 * @param groupName group_Name
	 */
	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	/**
	 * Get the group_Name.
	 * 
	 * @return group_Name
	 */
	public String getGroupName() {
		return this.groupName;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((groupName == null) ? 0 : groupName.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ItemGroup other = (ItemGroup) obj;
		if (groupName == null) {
			if (other.groupName != null) {
				return false;
			}
		} else if (!groupName.equals(other.groupName)) {
			return false;
		}
		return true;
	}

}
