package com.wingcode.suppermarket.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonRootName;

/**
 * Model class of item_Sub_Group.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table(name = "item_sub_sroup")
@JsonRootName(value = "ItemSubGroup")
public class ItemSubGroup extends AuditModel {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** sub_Group_Name. */
	@Id	
	@Column(name = "sub_Group_Name", nullable = false, updatable = false)
	private String subGroupName;

	/**
	 * Set the sub_Group_Name.
	 * 
	 * @param subGroupName
	 *            sub_Group_Name
	 */
	public void setSubGroupName(String subGroupName) {
		this.subGroupName = subGroupName;
	}

	/**
	 * Get the sub_Group_Name.
	 * 
	 * @return sub_Group_Name
	 */
	public String getSubGroupName() {
		return this.subGroupName;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((subGroupName == null) ? 0 : subGroupName.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ItemSubGroup other = (ItemSubGroup) obj;
		if (subGroupName == null) {
			if (other.subGroupName != null) {
				return false;
			}
		} else if (!subGroupName.equals(other.subGroupName)) {
			return false;
		}
		return true;
	}

}
