package com.wingcode.suppermarket.model;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of item_Sub_Group.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ItemSubGroup implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** sub_Group_Name. */
	private String subGroupName;

	/** The set of item. */
	private Set<Item> itemSet;

	/**
	 * Constructor.
	 */
	public ItemSubGroup() {
		this.itemSet = new HashSet<>();
	}

	/**
	 * Set the sub_Group_Name.
	 * 
	 * @param subGroupName
	 *            sub_Group_Name
	 */
	public void setSubGroupName(String subGroupName) {
		this.subGroupName = subGroupName;
	}

	/**
	 * Get the sub_Group_Name.
	 * 
	 * @return sub_Group_Name
	 */
	public String getSubGroupName() {
		return this.subGroupName;
	}

	/**
	 * Set the set of the item.
	 * 
	 * @param itemSet
	 *            The set of item
	 */
	public void setItemSet(Set<Item> itemSet) {
		this.itemSet = itemSet;
	}

	/**
	 * Add the item.
	 * 
	 * @param item
	 *            item
	 */
	public void addItem(Item item) {
		this.itemSet.add(item);
	}

	/**
	 * Get the set of the item.
	 * 
	 * @return The set of item
	 */
	public Set<Item> getItemSet() {
		return this.itemSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((subGroupName == null) ? 0 : subGroupName.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ItemSubGroup other = (ItemSubGroup) obj;
		if (subGroupName == null) {
			if (other.subGroupName != null) {
				return false;
			}
		} else if (!subGroupName.equals(other.subGroupName)) {
			return false;
		}
		return true;
	}

}
