package com.wingcode.suppermarket.model;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of purchase_Item.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class PurchaseItem implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** purchase_Item_Id. */
	private Long purchaseItemId;

	/** purchase. */
	private Purchase purchase;

	/** item. */
	private Item item;

	/** cost. */
	private Double cost;

	/** discount. */
	private Double discount;

	/** quantity. */
	private Double quantity;

	/** free_Quantity. */
	private Double freeQuantity;

	/** available_Quantity. */
	private Double availableQuantity;

	/** amount. */
	private Double amount;

	/** wholesale_Price. */
	private Double wholesalePrice;

	/** retail_Price. */
	private Double retailPrice;

	/** reorder_Level. */
	private Double reorderLevel;

	/** purchase_Date. */
	private Date purchaseDate;

	/** manufacture_Date. */
	private Date manufactureDate;

	/** expire_Date. */
	private Date expireDate;

	/** purchase_Type. */
	private String purchaseType;

	/** on_Update. */
	private Date onUpdate;

	/** The set of sale_Item. */
	private Set<SaleItem> saleItemSet;

	/**
	 * Constructor.
	 */
	public PurchaseItem() {
		this.saleItemSet = new HashSet<SaleItem>();
	}

	/**
	 * Set the purchase_Item_Id.
	 * 
	 * @param purchaseItemId
	 *            purchase_Item_Id
	 */
	public void setPurchaseItemId(Long purchaseItemId) {
		this.purchaseItemId = purchaseItemId;
	}

	/**
	 * Get the purchase_Item_Id.
	 * 
	 * @return purchase_Item_Id
	 */
	public Long getPurchaseItemId() {
		return this.purchaseItemId;
	}

	/**
	 * Set the purchase.
	 * 
	 * @param purchase
	 *            purchase
	 */
	public void setPurchase(Purchase purchase) {
		this.purchase = purchase;
	}

	/**
	 * Get the purchase.
	 * 
	 * @return purchase
	 */
	public Purchase getPurchase() {
		return this.purchase;
	}

	/**
	 * Set the item.
	 * 
	 * @param item
	 *            item
	 */
	public void setItem(Item item) {
		this.item = item;
	}

	/**
	 * Get the item.
	 * 
	 * @return item
	 */
	public Item getItem() {
		return this.item;
	}

	/**
	 * Set the cost.
	 * 
	 * @param cost
	 *            cost
	 */
	public void setCost(Double cost) {
		this.cost = cost;
	}

	/**
	 * Get the cost.
	 * 
	 * @return cost
	 */
	public Double getCost() {
		return this.cost;
	}

	/**
	 * Set the discount.
	 * 
	 * @param discount
	 *            discount
	 */
	public void setDiscount(Double discount) {
		this.discount = discount;
	}

	/**
	 * Get the discount.
	 * 
	 * @return discount
	 */
	public Double getDiscount() {
		return this.discount;
	}

	/**
	 * Set the quantity.
	 * 
	 * @param quantity
	 *            quantity
	 */
	public void setQuantity(Double quantity) {
		this.quantity = quantity;
	}

	/**
	 * Get the quantity.
	 * 
	 * @return quantity
	 */
	public Double getQuantity() {
		return this.quantity;
	}

	/**
	 * Set the free_Quantity.
	 * 
	 * @param freeQuantity
	 *            free_Quantity
	 */
	public void setFreeQuantity(Double freeQuantity) {
		this.freeQuantity = freeQuantity;
	}

	/**
	 * Get the free_Quantity.
	 * 
	 * @return free_Quantity
	 */
	public Double getFreeQuantity() {
		return this.freeQuantity;
	}

	/**
	 * Set the available_Quantity.
	 * 
	 * @param availableQuantity
	 *            available_Quantity
	 */
	public void setAvailableQuantity(Double availableQuantity) {
		this.availableQuantity = availableQuantity;
	}

	/**
	 * Get the available_Quantity.
	 * 
	 * @return available_Quantity
	 */
	public Double getAvailableQuantity() {
		return this.availableQuantity;
	}

	/**
	 * Set the amount.
	 * 
	 * @param amount
	 *            amount
	 */
	public void setAmount(Double amount) {
		this.amount = amount;
	}

	/**
	 * Get the amount.
	 * 
	 * @return amount
	 */
	public Double getAmount() {
		return this.amount;
	}

	/**
	 * Set the wholesale_Price.
	 * 
	 * @param wholesalePrice
	 *            wholesale_Price
	 */
	public void setWholesalePrice(Double wholesalePrice) {
		this.wholesalePrice = wholesalePrice;
	}

	/**
	 * Get the wholesale_Price.
	 * 
	 * @return wholesale_Price
	 */
	public Double getWholesalePrice() {
		return this.wholesalePrice;
	}

	/**
	 * Set the retail_Price.
	 * 
	 * @param retailPrice
	 *            retail_Price
	 */
	public void setRetailPrice(Double retailPrice) {
		this.retailPrice = retailPrice;
	}

	/**
	 * Get the retail_Price.
	 * 
	 * @return retail_Price
	 */
	public Double getRetailPrice() {
		return this.retailPrice;
	}

	/**
	 * Set the reorder_Level.
	 * 
	 * @param reorderLevel
	 *            reorder_Level
	 */
	public void setReorderLevel(Double reorderLevel) {
		this.reorderLevel = reorderLevel;
	}

	/**
	 * Get the reorder_Level.
	 * 
	 * @return reorder_Level
	 */
	public Double getReorderLevel() {
		return this.reorderLevel;
	}

	/**
	 * Set the purchase_Date.
	 * 
	 * @param purchaseDate
	 *            purchase_Date
	 */
	public void setPurchaseDate(Date purchaseDate) {
		this.purchaseDate = purchaseDate;
	}

	/**
	 * Get the purchase_Date.
	 * 
	 * @return purchase_Date
	 */
	public Date getPurchaseDate() {
		return this.purchaseDate;
	}

	/**
	 * Set the manufacture_Date.
	 * 
	 * @param manufactureDate
	 *            manufacture_Date
	 */
	public void setManufactureDate(Date manufactureDate) {
		this.manufactureDate = manufactureDate;
	}

	/**
	 * Get the manufacture_Date.
	 * 
	 * @return manufacture_Date
	 */
	public Date getManufactureDate() {
		return this.manufactureDate;
	}

	/**
	 * Set the expire_Date.
	 * 
	 * @param expireDate
	 *            expire_Date
	 */
	public void setExpireDate(Date expireDate) {
		this.expireDate = expireDate;
	}

	/**
	 * Get the expire_Date.
	 * 
	 * @return expire_Date
	 */
	public Date getExpireDate() {
		return this.expireDate;
	}

	/**
	 * Set the purchase_Type.
	 * 
	 * @param purchaseType
	 *            purchase_Type
	 */
	public void setPurchaseType(String purchaseType) {
		this.purchaseType = purchaseType;
	}

	/**
	 * Get the purchase_Type.
	 * 
	 * @return purchase_Type
	 */
	public String getPurchaseType() {
		return this.purchaseType;
	}

	/**
	 * Set the on_Update.
	 * 
	 * @param onUpdate
	 *            on_Update
	 */
	public void setOnUpdate(Date onUpdate) {
		this.onUpdate = onUpdate;
	}

	/**
	 * Get the on_Update.
	 * 
	 * @return on_Update
	 */
	public Date getOnUpdate() {
		return this.onUpdate;
	}

	/**
	 * Set the set of the sale_Item.
	 * 
	 * @param saleItemSet
	 *            The set of sale_Item
	 */
	public void setSaleItemSet(Set<SaleItem> saleItemSet) {
		this.saleItemSet = saleItemSet;
	}

	/**
	 * Add the sale_Item.
	 * 
	 * @param saleItem
	 *            sale_Item
	 */
	public void addSaleItem(SaleItem saleItem) {
		this.saleItemSet.add(saleItem);
	}

	/**
	 * Get the set of the sale_Item.
	 * 
	 * @return The set of sale_Item
	 */
	public Set<SaleItem> getSaleItemSet() {
		return this.saleItemSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((purchaseItemId == null) ? 0 : purchaseItemId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		PurchaseItem other = (PurchaseItem) obj;
		if (purchaseItemId == null) {
			if (other.purchaseItemId != null) {
				return false;
			}
		} else if (!purchaseItemId.equals(other.purchaseItemId)) {
			return false;
		}
		return true;
	}

}
