package com.wingcode.suppermarket.model;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of sale_Item.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class SaleItem implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** sale_Item_Id. */
	private Long saleItemId;

	/** issue_No. */
	private Integer issueNo;

	/** sale_Date. */
	private Date saleDate;

	/** sale_Invoice. */
	private SaleInvoice saleInvoice;

	/** item. */
	private Item item;

	/** purchase_Item. */
	private PurchaseItem purchaseItem;

	/** cost. */
	private Double cost;

	/** sale_Price. */
	private Double salePrice;

	/** discount. */
	private Double discount;

	/** quantity. */
	private Double quantity;

	/** amount. */
	private Double amount;

	/** net_Amount. */
	private Double netAmount;

	/** sale_Day. */
	private Integer saleDay;

	/** sale_Month. */
	private Integer saleMonth;

	/** sale_Year. */
	private Integer saleYear;

	/** user. */
	private User user;
	

	/**
	 * Set the sale_Item_Id.
	 * 
	 * @param saleItemId
	 *            sale_Item_Id
	 */
	public void setSaleItemId(Long saleItemId) {
		this.saleItemId = saleItemId;
	}

	/**
	 * Get the sale_Item_Id.
	 * 
	 * @return sale_Item_Id
	 */
	public Long getSaleItemId() {
		return this.saleItemId;
	}

	/**
	 * Set the issue_No.
	 * 
	 * @param issueNo
	 *            issue_No
	 */
	public void setIssueNo(Integer issueNo) {
		this.issueNo = issueNo;
	}

	/**
	 * Get the issue_No.
	 * 
	 * @return issue_No
	 */
	public Integer getIssueNo() {
		return this.issueNo;
	}

	/**
	 * Set the sale_Date.
	 * 
	 * @param saleDate
	 *            sale_Date
	 */
	public void setSaleDate(Date saleDate) {
		this.saleDate = saleDate;
	}

	/**
	 * Get the sale_Date.
	 * 
	 * @return sale_Date
	 */
	public Date getSaleDate() {
		return this.saleDate;
	}

	/**
	 * Set the sale_Invoice.
	 * 
	 * @param saleInvoice
	 *            sale_Invoice
	 */
	public void setSaleInvoice(SaleInvoice saleInvoice) {
		this.saleInvoice = saleInvoice;
	}

	/**
	 * Get the sale_Invoice.
	 * 
	 * @return sale_Invoice
	 */
	public SaleInvoice getSaleInvoice() {
		return this.saleInvoice;
	}

	/**
	 * Set the item.
	 * 
	 * @param item
	 *            item
	 */
	public void setItem(Item item) {
		this.item = item;
	}

	/**
	 * Get the item.
	 * 
	 * @return item
	 */
	public Item getItem() {
		return this.item;
	}

	/**
	 * Set the purchase_Item.
	 * 
	 * @param purchaseItem
	 *            purchase_Item
	 */
	public void setPurchaseItem(PurchaseItem purchaseItem) {
		this.purchaseItem = purchaseItem;
	}

	/**
	 * Get the purchase_Item.
	 * 
	 * @return purchase_Item
	 */
	public PurchaseItem getPurchaseItem() {
		return this.purchaseItem;
	}

	/**
	 * Set the cost.
	 * 
	 * @param cost
	 *            cost
	 */
	public void setCost(Double cost) {
		this.cost = cost;
	}

	/**
	 * Get the cost.
	 * 
	 * @return cost
	 */
	public Double getCost() {
		return this.cost;
	}

	/**
	 * Set the sale_Price.
	 * 
	 * @param salePrice
	 *            sale_Price
	 */
	public void setSalePrice(Double salePrice) {
		this.salePrice = salePrice;
	}

	/**
	 * Get the sale_Price.
	 * 
	 * @return sale_Price
	 */
	public Double getSalePrice() {
		return this.salePrice;
	}

	/**
	 * Set the discount.
	 * 
	 * @param discount
	 *            discount
	 */
	public void setDiscount(Double discount) {
		this.discount = discount;
	}

	/**
	 * Get the discount.
	 * 
	 * @return discount
	 */
	public Double getDiscount() {
		return this.discount;
	}

	/**
	 * Set the quantity.
	 * 
	 * @param quantity
	 *            quantity
	 */
	public void setQuantity(Double quantity) {
		this.quantity = quantity;
	}

	/**
	 * Get the quantity.
	 * 
	 * @return quantity
	 */
	public Double getQuantity() {
		return this.quantity;
	}

	/**
	 * Set the amount.
	 * 
	 * @param amount
	 *            amount
	 */
	public void setAmount(Double amount) {
		this.amount = amount;
	}

	/**
	 * Get the amount.
	 * 
	 * @return amount
	 */
	public Double getAmount() {
		return this.amount;
	}

	/**
	 * Set the net_Amount.
	 * 
	 * @param netAmount
	 *            net_Amount
	 */
	public void setNetAmount(Double netAmount) {
		this.netAmount = netAmount;
	}

	/**
	 * Get the net_Amount.
	 * 
	 * @return net_Amount
	 */
	public Double getNetAmount() {
		return this.netAmount;
	}

	/**
	 * Set the sale_Day.
	 * 
	 * @param saleDay
	 *            sale_Day
	 */
	public void setSaleDay(Integer saleDay) {
		this.saleDay = saleDay;
	}

	/**
	 * Get the sale_Day.
	 * 
	 * @return sale_Day
	 */
	public Integer getSaleDay() {
		return this.saleDay;
	}

	/**
	 * Set the sale_Month.
	 * 
	 * @param saleMonth
	 *            sale_Month
	 */
	public void setSaleMonth(Integer saleMonth) {
		this.saleMonth = saleMonth;
	}

	/**
	 * Get the sale_Month.
	 * 
	 * @return sale_Month
	 */
	public Integer getSaleMonth() {
		return this.saleMonth;
	}

	/**
	 * Set the sale_Year.
	 * 
	 * @param saleYear
	 *            sale_Year
	 */
	public void setSaleYear(Integer saleYear) {
		this.saleYear = saleYear;
	}

	/**
	 * Get the sale_Year.
	 * 
	 * @return sale_Year
	 */
	public Integer getSaleYear() {
		return this.saleYear;
	}

	/**
	 * Set the user.
	 * 
	 * @param user
	 *            user
	 */
	public void setUser(User user) {
		this.user = user;
	}

	/**
	 * Get the user.
	 * 
	 * @return user
	 */
	public User getUser() {
		return this.user;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((saleItemId == null) ? 0 : saleItemId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		SaleItem other = (SaleItem) obj;
		if (saleItemId == null) {
			if (other.saleItemId != null) {
				return false;
			}
		} else if (!saleItemId.equals(other.saleItemId)) {
			return false;
		}
		return true;
	}

}
