package com.wingcode.suppermarket.model;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonRootName;

/**
 * Model class of supplier.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Entity
@Table(name = "supplier")
@JsonRootName(value = "Supplier")
public class Supplier extends AuditModel {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** supplier_Id. */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "supplier_Id")
	private Long supplierId;

	/** suplier_Code. */
	@Column(name = "suplier_Code")
	private String suplierCode;

	/** supplier_Name. */
	@Column(name = "supplier_Name")
	private String supplierName;

	/** supplier_Address. */
	@Column(name = "supplier_Address")
	private String supplierAddress;

	/** supplier_Contact. */
	@Column(name = "supplier_Contact")
	private String supplierContact;

	/** description. */
	@Column(name = "description")
	private String description;

	/** on_Update. */
	@Column(name = "on_Update")
	private Date onUpdate;

	
	/**
	 * Set the supplier_Id.
	 * 
	 * @param supplierId
	 *            supplier_Id
	 */
	public void setSupplierId(Long supplierId) {
		this.supplierId = supplierId;
	}

	/**
	 * Get the supplier_Id.
	 * 
	 * @return supplier_Id
	 */
	public Long getSupplierId() {
		return this.supplierId;
	}

	/**
	 * Set the suplier_Code.
	 * 
	 * @param suplierCode
	 *            suplier_Code
	 */
	public void setSuplierCode(String suplierCode) {
		this.suplierCode = suplierCode;
	}

	/**
	 * Get the suplier_Code.
	 * 
	 * @return suplier_Code
	 */
	public String getSuplierCode() {
		return this.suplierCode;
	}

	/**
	 * Set the supplier_Name.
	 * 
	 * @param supplierName
	 *            supplier_Name
	 */
	public void setSupplierName(String supplierName) {
		this.supplierName = supplierName;
	}

	/**
	 * Get the supplier_Name.
	 * 
	 * @return supplier_Name
	 */
	public String getSupplierName() {
		return this.supplierName;
	}

	/**
	 * Set the supplier_Address.
	 * 
	 * @param supplierAddress
	 *            supplier_Address
	 */
	public void setSupplierAddress(String supplierAddress) {
		this.supplierAddress = supplierAddress;
	}

	/**
	 * Get the supplier_Address.
	 * 
	 * @return supplier_Address
	 */
	public String getSupplierAddress() {
		return this.supplierAddress;
	}

	/**
	 * Set the supplier_Contact.
	 * 
	 * @param supplierContact
	 *            supplier_Contact
	 */
	public void setSupplierContact(String supplierContact) {
		this.supplierContact = supplierContact;
	}

	/**
	 * Get the supplier_Contact.
	 * 
	 * @return supplier_Contact
	 */
	public String getSupplierContact() {
		return this.supplierContact;
	}

	/**
	 * Set the description.
	 * 
	 * @param description
	 *            description
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * Get the description.
	 * 
	 * @return description
	 */
	public String getDescription() {
		return this.description;
	}

	/**
	 * Set the on_Update.
	 * 
	 * @param onUpdate
	 *            on_Update
	 */
	public void setOnUpdate(Date onUpdate) {
		this.onUpdate = onUpdate;
	}

	/**
	 * Get the on_Update.
	 * 
	 * @return on_Update
	 */
	public Date getOnUpdate() {
		return this.onUpdate;
	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((supplierId == null) ? 0 : supplierId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Supplier other = (Supplier) obj;
		if (supplierId == null) {
			if (other.supplierId != null) {
				return false;
			}
		} else if (!supplierId.equals(other.supplierId)) {
			return false;
		}
		return true;
	}

}
