package com.wingcode.suppermarket.model;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of user.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class User implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** user_Id. */
	private Integer userId;

	/** name. */
	private String name;

	/** email. */
	private String email;

	/** password. */
	private String password;

	/** The set of purchase. */
	private Set<Purchase> purchaseSet;

	/** The set of sale_Invoice. */
	private Set<SaleInvoice> saleInvoiceSet;

	/** The set of sale_Item. */
	private Set<SaleItem> saleItemSet;

	/**
	 * Constructor.
	 */
	public User() {
		this.purchaseSet = new HashSet<Purchase>();
		this.saleInvoiceSet = new HashSet<SaleInvoice>();
		this.saleItemSet = new HashSet<SaleItem>();
	}

	/**
	 * Set the user_Id.
	 * 
	 * @param userId
	 *            user_Id
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * Get the user_Id.
	 * 
	 * @return user_Id
	 */
	public Integer getUserId() {
		return this.userId;
	}

	/**
	 * Set the name.
	 * 
	 * @param name
	 *            name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Get the name.
	 * 
	 * @return name
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Set the email.
	 * 
	 * @param email
	 *            email
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * Get the email.
	 * 
	 * @return email
	 */
	public String getEmail() {
		return this.email;
	}

	/**
	 * Set the password.
	 * 
	 * @param password
	 *            password
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * Get the password.
	 * 
	 * @return password
	 */
	public String getPassword() {
		return this.password;
	}

	/**
	 * Set the set of the purchase.
	 * 
	 * @param purchaseSet
	 *            The set of purchase
	 */
	public void setPurchaseSet(Set<Purchase> purchaseSet) {
		this.purchaseSet = purchaseSet;
	}

	/**
	 * Add the purchase.
	 * 
	 * @param purchase
	 *            purchase
	 */
	public void addPurchase(Purchase purchase) {
		this.purchaseSet.add(purchase);
	}

	/**
	 * Get the set of the purchase.
	 * 
	 * @return The set of purchase
	 */
	public Set<Purchase> getPurchaseSet() {
		return this.purchaseSet;
	}

	/**
	 * Set the set of the sale_Invoice.
	 * 
	 * @param saleInvoiceSet
	 *            The set of sale_Invoice
	 */
	public void setSaleInvoiceSet(Set<SaleInvoice> saleInvoiceSet) {
		this.saleInvoiceSet = saleInvoiceSet;
	}

	/**
	 * Add the sale_Invoice.
	 * 
	 * @param saleInvoice
	 *            sale_Invoice
	 */
	public void addSaleInvoice(SaleInvoice saleInvoice) {
		this.saleInvoiceSet.add(saleInvoice);
	}

	/**
	 * Get the set of the sale_Invoice.
	 * 
	 * @return The set of sale_Invoice
	 */
	public Set<SaleInvoice> getSaleInvoiceSet() {
		return this.saleInvoiceSet;
	}

	/**
	 * Set the set of the sale_Item.
	 * 
	 * @param saleItemSet
	 *            The set of sale_Item
	 */
	public void setSaleItemSet(Set<SaleItem> saleItemSet) {
		this.saleItemSet = saleItemSet;
	}

	/**
	 * Add the sale_Item.
	 * 
	 * @param saleItem
	 *            sale_Item
	 */
	public void addSaleItem(SaleItem saleItem) {
		this.saleItemSet.add(saleItem);
	}

	/**
	 * Get the set of the sale_Item.
	 * 
	 * @return The set of sale_Item
	 */
	public Set<SaleItem> getSaleItemSet() {
		return this.saleItemSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((userId == null) ? 0 : userId.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		User other = (User) obj;
		if (userId == null) {
			if (other.userId != null) {
				return false;
			}
		} else if (!userId.equals(other.userId)) {
			return false;
		}
		return true;
	}

}
